name: medilab_prokit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  image_picker: ^1.1.2
  flutter:
    sdk: flutter

  # CSV export
  csv: ^6.0.0

  # Base
  cupertino_icons: ^1.0.8
  nb_utils: ^7.1.7+2
  intl: ^0.20.2
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  mobx: ^2.3.0
  flutter_mobx: ^2.1.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  country_code_picker: ^3.0.0
  percent_indicator: ^4.2.3
  otp_text_field: ^1.1.3
  url_launcher: ^6.2.6

  # RxMind dependencies
  sqflite: ^2.4.2
  path_provider: ^2.1.4
  uuid: ^4.4.0
  awesome_notifications: ^0.10.1
  go_router: ^16.0.0
  provider: ^6.1.2
  flutter_local_notifications: ^19.4.0
  flutter_dotenv: ^5.1.1
  fl_chart: ^1.0.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  google_mlkit_text_recognition: ^0.15.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.8
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
