name: medilab_prokit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  image_picker: ^1.0.7
  flutter:
    sdk: flutter

  # CSV export
  csv: ^5.0.2

  # Base
  cupertino_icons: ^1.0.4
  nb_utils: ^6.0.7
  intl: ^0.19.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.2.0
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  cached_network_image: ^3.1.0
  flutter_staggered_grid_view: ^0.4.0
  country_code_picker: 2.0.2
  percent_indicator: ^3.0.1
  otp_text_field: ^1.1.1
  url_launcher: ^6.0.18

  # RxMind dependencies
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  uuid: ^4.3.3
  awesome_notifications: ^0.9.2
  go_router: ^13.2.2
  provider: ^6.1.2
  flutter_local_notifications: ^17.1.2
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.66.2
  connectivity_plus: ^5.0.0
  shared_preferences: ^2.2.3
  google_mlkit_text_recognition: ^0.15.0
  shimmer: ^3.0.0
  lottie: ^3.0.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/lottie/clipboard.json
    - assets/lottie/confetti.json
    - assets/lottie/gear.json
    - assets/audio/victory.mp3

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
