name: rxmind_app
description: RxMind - Your On-Device Guide to Safe Hospital Discharge
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.7
  path_provider: ^2.0.15
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  smooth_page_indicator:
  provider:
  font_awesome_flutter:
  flutter_secure_storage:
  sqflite:
  archive:
  file_picker:
  device_info_plus: ^9.1.2
  google_ml_kit: ^0.18.0
  syncfusion_flutter_charts:
  flutter_local_notifications: ^17.0.0
  flutter_slidable:
  flutter_tesseract_ocr: ^0.4.30
  google_gemini:
  image_picker: ^1.2.0
  flutter_dotenv: ^5.0.2
  permission_handler: ^11.3.0
  flutter_markdown: ^0.7.4+1
  pdfx: ^2.5.0
  path: ^1.8.3
  timezone: ^0.9.2
  # Add other dependencies as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/illus/logo.svg
    - assets/illus/onboard1.svg
    - assets/illus/onboard2.svg
    - assets/illus/onboard3.svg
    - .env
    - assets/tessdata/
    - assets/tessdata/README.md
    - assets/tessdata_config.json
    # Add other assets as needed
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
